services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-moneymaker}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres123}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moneymaker-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-postgres}']
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - moneymaker-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - moneymaker-network

  # Aplicação NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-30d}
      DATABASE_URL: postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres123}@postgres:5432/${DATABASE_NAME:-moneymaker}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # Variáveis para Telegram
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-8393105211:AAE7_e8KG5cgoe0FZgz6RlGppDefLKopBlg}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-7201413321}
      TELEGRAM_TIMEOUT: ${TELEGRAM_TIMEOUT:-30000}
      TELEGRAM_CONNECT_TIMEOUT: ${TELEGRAM_CONNECT_TIMEOUT:-15000}
      TELEGRAM_READ_TIMEOUT: ${TELEGRAM_READ_TIMEOUT:-30000}
      TELEGRAM_MAX_RETRIES: ${TELEGRAM_MAX_RETRIES:-3}
      TELEGRAM_RETRY_DELAY: ${TELEGRAM_RETRY_DELAY:-2000}
      # Variáveis para Prometheus (caso precise)
      PROMETHEUS_METRICS_PORT: 9091
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - moneymaker-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:

networks:
  moneymaker-network:
    driver: bridge
